CREATE TABLE bot_stats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cpu_percent DOUBLE NOT NULL,
    memory_usage DOUBLE NOT NULL,
    heap_used DOUBLE NOT NULL,
    uptime BIGINT NOT NULL COMMENT 'Uptime in nanoseconds',
    servers INT NOT NULL,
    msg_cache_size INT NOT NULL,
    max_msg_cache_size INT NOT NULL,
    member_count INT NOT NULL,
    channel_count INT NOT NULL,
    role_count INT NOT NULL,
    emote_count INT NOT NULL,
    event_queue_size INT NOT NULL,
    discord_ping_ms INT NOT NULL,
    redis_ping_ms INT NOT NULL,
    db_ping_ms INT NOT NULL,
    redis_size_mb DOUBLE NOT NULL,
    db_size_mb DOUBLE NOT NULL,
    commands_run INT NOT NULL,
    total_cases INT NOT NULL,
    total_tickets INT NOT NULL,
    total_appeals INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
